#!/bin/sh

set -e

case "$1" in 
    upgrade)
    ;;  
    remove)
        deb-systemd-helper disable jasper-bot.service >/dev/null
        deb-systemd-invoke stop jasper-bot.service >/dev/null
    ;;
    *)
    ;;
esac

exit 0